# Generated by Django 4.2.7 on 2023-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_peliculas', '0002_rename_peliculas_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cover',
            field=models.URLField(blank=True, help_text='Link de la portada de la pelicula'),
        ),
    ]
