# Generated by Django 4.2.7 on 2023-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_peliculas', '0003_pelicula_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Comedia', 'Comedia'), ('Horror', 'Horror'), ('Fantasia', 'Fantasia'), ('Acción', 'Acción'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Misterio', 'Misterio')], max_length=10),
        ),
    ]
